# Generated by Django 5.2.9 on 2025-12-11 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_carton', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Numéro carton')),
                ('operateur', models.CharField(choices=[('Bouygues', 'Bouygues')], max_length=100, verbose_name='Opérateur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
            ],
            options={
                'verbose_name': 'Carton',
                'verbose_name_plural': 'Cartons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Code poste')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('base_operationnelle', models.CharField(choices=[('BO Nord', 'BO Nord'), ('BO Centre', 'BO Centre'), ('BO Sud', 'BO Sud')], max_length=20, verbose_name='Base opérationnelle')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Poste',
                'verbose_name_plural': 'Postes',
                'ordering': ['base_operationnelle', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Concentrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_serie', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='N° série')),
                ('operateur', models.CharField(max_length=100, verbose_name='Opérateur')),
                ('affectation', models.CharField(blank=True, choices=[('Magasin', 'Magasin'), ('BO Nord', 'BO Nord'), ('BO Centre', 'BO Centre'), ('BO Sud', 'BO Sud'), ('Labo', 'Labo')], default='', max_length=20, verbose_name='Affectation')),
                ('etat', models.CharField(choices=[('en_livraison', 'En livraison'), ('en_stock', 'En stock'), ('pose', 'Posé'), ('a_tester', 'À tester'), ('HS', 'Hors service')], default='en_livraison', max_length=20, verbose_name='État')),
                ('date_affectation', models.DateField(blank=True, null=True, verbose_name='Date affectation')),
                ('date_pose', models.DateField(blank=True, null=True, verbose_name='Date pose')),
                ('date_dernier_etat', models.DateField(auto_now=True, verbose_name='Date dernier état')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('carton', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concentrateurs', to='inventory.carton', verbose_name='Carton')),
                ('poste_pose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concentrateurs_poses', to='inventory.poste', verbose_name='Poste de pose')),
            ],
            options={
                'verbose_name': 'Concentrateur',
                'verbose_name_plural': 'Concentrateurs',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['etat', 'affectation'], name='inventory_c_etat_681aa4_idx'), models.Index(fields=['operateur'], name='inventory_c_operate_d88b77_idx'), models.Index(fields=['carton', 'etat'], name='inventory_c_carton__2898bf_idx')],
            },
        ),
    ]
