# Generated by Django 5.2.9 on 2025-12-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carton",
            name="is_reconditionne",
            field=models.BooleanField(default=False, verbose_name="Reconditionné"),
        ),
        migrations.AlterField(
            model_name="carton",
            name="operateur",
            field=models.CharField(
                choices=[
                    ("Bouygues", "Bouygues"),
                    ("Orange", "Orange"),
                    ("SFR", "SFR"),
                ],
                max_length=100,
                verbose_name="Opérateur",
            ),
        ),
    ]
