# Generated by Django 5.2.9 on 2025-12-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_carton_is_reconditionne_alter_carton_operateur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concentrateur",
            name="etat",
            field=models.CharField(
                choices=[
                    ("en_livraison", "En livraison"),
                    ("en_stock", "En stock"),
                    ("pose", "Posé"),
                    ("a_tester", "À tester"),
                    ("en_attente_recond", "En attente reconditionnement"),
                    ("HS", "Hors service"),
                ],
                default="en_livraison",
                max_length=20,
                verbose_name="État",
            ),
        ),
    ]
