# Generated by Django 5.2.9 on 2025-12-11 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_carton_operateur'),
        ('inventory', '0003_alter_concentrateur_etat'),
    ]

    operations = [
    ]
