# Generated by Django 5.2.9 on 2025-12-11 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('reception', 'Réception magasin'), ('commande_bo', 'Commande vers BO'), ('pose', 'Pose sur poste'), ('depose', 'Dépose du poste'), ('test_ok', 'Test OK'), ('test_hs', 'Test HS'), ('modification', 'Modification manuelle')], max_length=20, verbose_name='Action')),
                ('ancien_etat', models.CharField(blank=True, default='', max_length=20, verbose_name='Ancien état')),
                ('nouvel_etat', models.CharField(blank=True, default='', max_length=20, verbose_name='Nouvel état')),
                ('ancienne_affectation', models.CharField(blank=True, default='', max_length=20, verbose_name='Ancienne affectation')),
                ('nouvelle_affectation', models.CharField(blank=True, default='', max_length=20, verbose_name='Nouvelle affectation')),
                ('poste', models.CharField(blank=True, default='', max_length=100, verbose_name='Poste')),
                ('commentaire', models.TextField(blank=True, default='', verbose_name='Commentaire')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date/Heure')),
                ('concentrateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='inventory.concentrateur', verbose_name='Concentrateur')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Historique',
                'verbose_name_plural': 'Historiques',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['concentrateur', '-timestamp'], name='tracking_hi_concent_ee629b_idx'), models.Index(fields=['action', 'timestamp'], name='tracking_hi_action_5bb0b3_idx'), models.Index(fields=['user', 'timestamp'], name='tracking_hi_user_id_61f01f_idx')],
            },
        ),
    ]
