# Generated by Django 5.2.9 on 2025-12-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historique",
            name="action",
            field=models.CharField(
                choices=[
                    ("reception", "Réception magasin"),
                    ("commande_bo", "Commande vers BO"),
                    ("pose", "Pose sur poste"),
                    ("depose", "Dépose du poste"),
                    ("test_ok", "Test OK"),
                    ("test_hs", "Test HS"),
                    ("reconditionnement", "Reconditionnement"),
                    ("modification", "Modification manuelle"),
                ],
                max_length=20,
                verbose_name="Action",
            ),
        ),
    ]
